// <auto-generated />
namespace Driving.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DrivingDB23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DrivingDB23));
        
        string IMigrationMetadata.Id
        {
            get { return "202110071924123_DrivingDB23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
